
services:
  honeypot:
    build: .
    image: honeypot_agent:latest
    container_name: honeypot_agent
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8186:8186"  
      - "2222:2222"
    environment:
      - OPENAI_API_KEY= 
    volumes:
      - .:/app
    restart: unless-stopped
